### ISSUE TITLE
[Feature] GDPR Tracking Compliance

### ISSUE THREAD

**Issue by xHayden** [GTBitsOfGood/jennifer-anns-group#174]
## Context
Following GDPR, we need to tell users that their data is being tracked. To accomplish this, we're prompting users in account creation if they'll allow us to keep their data.

### Frontend
- Update user registration to require accepting our privacy policy.
- Create private policy modal as described in figma.
- Check the box on default.
- Create setting in user account settings to turn off the property.
- Update context to check if the user has the logging property before logging on client. The property will be on the user's auth token.

### Backend
- Create api route to set and unset a user's logging permissions.
- Check this permission in the middleware responsible for logging to bog analytics, if it isn't set, don't log anything.
- Create "tracked" property on users that is true on default.

## Acceptance Criteria
- [ ] Create tracked property on users.
- [ ] Update user registration flow to add privacy policy.
- [ ] Update user settings to add privacy option.
- [ ] Create API route to change logging permissions.
- [ ] Update middleware to not track when logging is not set.
- [ ] Update context to not log if logging isn't set.

## Notes
[Updated Registration on Figma](https://www.figma.com/design/mgIynQl7FOJ10aAEdBy5u6/Jennifer-Annes-F24?node-id=16310-4049&t=OpIAsqc88Mqa5swB-1)
Use the same text/modal on the settings menu as you see fit.

[More info on our GDPR requirements](https://www.notion.so/gtbitsofgood/GDPR-Compliance-Checklist-70840342629a41beb634eff4f6c1cb08?pvs=4)
